"""Small, explicitly illustrative Kochi catalog; estimates are not live facts."""


def place(id, name, category, lat, lng, cost, duration, hours, tip, scores, count=24):
    return dict(
        id=id,
        name=name,
        category=category,
        lat=lat,
        lng=lng,
        cost=cost,
        duration=duration,
        opens=hours[0],
        closes=hours[1],
        tip=tip,
        slh=dict(
            safety=scores[0],
            legitimacy=scores[1],
            hygiene=scores[2],
            reviews=count,
            reviewed_at="2026-09-01",
            source="Illustrative seed data",
        ),
        demo=True,
    )


PLACES = [
    place(
        "nets",
        "Chinese Fishing Nets",
        "Nature",
        9.9677,
        76.2425,
        0,
        60,
        (8, 18),
        "Go early for softer light. Ask before photographing working fishers.",
        (4.5, 4.8, 4.2),
    ),
    place(
        "church",
        "St. Francis Church",
        "Culture",
        9.9657,
        76.241,
        0,
        45,
        (9, 17),
        "Dress respectfully and keep your voice low inside.",
        (4.7, 4.9, 4.5),
    ),
    place(
        "kashi",
        "Kashi Art Café",
        "Food",
        9.9656,
        76.2428,
        350,
        60,
        (9, 18),
        "Leave time to enjoy the art alongside your coffee.",
        (4.6, 4.7, 4.6),
    ),
    place(
        "beach",
        "Fort Kochi Beach",
        "Nature",
        9.9638,
        76.2387,
        0,
        75,
        (8, 18),
        "Enjoy the shoreline walk; this plan does not recommend swimming.",
        (4.2, 4.8, 3.8),
    ),
    place(
        "palace",
        "Mattancherry Palace",
        "Culture",
        9.9579,
        76.2595,
        100,
        75,
        (10, 17),
        "Confirm the opening day before visiting; the murals deserve a slow look.",
        (4.6, 4.9, 4.5),
    ),
    place(
        "jewtown",
        "Jew Town",
        "Culture",
        9.9572,
        76.2591,
        0,
        60,
        (9, 18),
        "Browse the small shops and ask before taking photos inside.",
        (4.4, 4.6, 4.2),
    ),
    place(
        "synagogue",
        "Paradesi Synagogue",
        "Culture",
        9.9578,
        76.2593,
        50,
        45,
        (10, 16),
        "Religious holidays can change access. Check locally before setting out.",
        (4.6, 4.9, 4.6),
    ),
    place(
        "cafe",
        "Mattancherry Tea Stop",
        "Food",
        9.9583,
        76.2598,
        150,
        45,
        (10, 18),
        "Illustrative food stop: choose a clearly priced, well-maintained local café.",
        (4.3, 4.3, 4.5),
    ),
    place(
        "market",
        "Spice Market Walk",
        "Food",
        9.9555,
        76.2601,
        100,
        60,
        (9, 17),
        "Compare prices and buy spices in clearly labeled, sealed packs.",
        (4.3, 4.4, 4.2),
    ),
    place(
        "sadya",
        "Kerala Sadya Lunch",
        "Food",
        9.9587,
        76.2585,
        350,
        75,
        (12, 15),
        "Illustrative lunch stop. Ask about ingredients and allergens before ordering.",
        (4.5, 4.5, 4.6),
    ),
    place(
        "promenade",
        "Marine Drive Promenade",
        "Nature",
        9.9814,
        76.2753,
        0,
        60,
        (8, 18),
        "Use the public waterfront paths and carry drinking water.",
        (4.3, 4.7, 4.0),
    ),
    place(
        "park",
        "Subhash Bose Park",
        "Nature",
        9.9695,
        76.2771,
        0,
        60,
        (10, 18),
        "Take a quiet break and use the marked waste bins.",
        (4.5, 4.8, 4.4),
    ),
    place(
        "island",
        "Willingdon Island Viewpoint",
        "Nature",
        9.9496,
        76.2756,
        100,
        75,
        (9, 17),
        "Stay in public areas; some island facilities have restricted access.",
        (4.2, 4.5, 4.1),
    ),
    place(
        "gallery",
        "David Hall Gallery",
        "Art",
        9.9638,
        76.2405,
        100,
        60,
        (10, 17),
        "Check which exhibition is on before your visit.",
        (4.6, 4.8, 4.6),
    ),
    place(
        "basilica",
        "Santa Cruz Basilica",
        "Culture",
        9.9632,
        76.2431,
        0,
        45,
        (9, 17),
        "Plan around services and respect photography restrictions.",
        (4.7, 4.9, 4.6),
    ),
    place(
        "theatre",
        "Kerala Kathakali Centre",
        "Art",
        9.9631,
        76.2433,
        500,
        90,
        (15, 19),
        "Confirm performance times and tickets with the venue.",
        (4.6, 4.8, 4.4),
    ),
    place(
        "princess",
        "Princess Street",
        "Hidden gems",
        9.9661,
        76.2421,
        0,
        45,
        (9, 18),
        "Look up at the old façades and stop into independent shops.",
        (4.4, 4.6, 4.3),
    ),
    place(
        "ferry",
        "Fort Kochi Ferry Waterfront",
        "Hidden gems",
        9.9673,
        76.2448,
        50,
        45,
        (8, 18),
        "Watch the ferries from public areas. Boat tickets are not included.",
        (4.2, 4.7, 4.0),
    ),
]
BY_ID = {p["id"]: p for p in PLACES}
TEMPLATE_STOPS = {
    "slow-kochi": [
        "nets",
        "church",
        "kashi",
        "beach",
        "palace",
        "jewtown",
        "cafe",
        "promenade",
    ],
    "heritage-trail": ["palace", "jewtown", "synagogue", "cafe"],
    "taste-kochi": ["kashi", "market", "sadya", "cafe"],
    "coastal-reset": [
        "nets",
        "beach",
        "promenade",
        "park",
        "island",
        "kashi",
        "cafe",
        "market",
        "sadya",
    ],
}


def slh_score(slh):
    values = [slh.get(k) for k in ("safety", "legitimacy", "hygiene")]
    if any(
        not isinstance(v, (float, int)) or isinstance(v, bool) or not 1 <= v <= 5 for v in values
    ):
        return None
    return round(sum(values) / 15 * 100)
