"""Illustrative citywide Kochi catalog; estimates are not live facts."""

import json
import re
from pathlib import Path

REGIONS = [
    {"id": "fort-kochi", "name": "Fort Kochi", "character": "Waterfront heritage and art"},
    {"id": "mattancherry", "name": "Mattancherry", "character": "Markets and layered history"},
    {"id": "ernakulam", "name": "Ernakulam & Marine Drive", "character": "Downtown and waterfront"},
    {"id": "panampilly", "name": "Panampilly Nagar", "character": "Cafés, parks and design"},
    {"id": "kadavanthra", "name": "Kadavanthra", "character": "Neighbourhood food and city life"},
    {"id": "edappally", "name": "Edappally", "character": "Shopping, culture and metro access"},
    {"id": "palarivattom", "name": "Palarivattom & Kaloor", "character": "Markets, food and sport"},
    {"id": "vyttila", "name": "Vyttila", "character": "Water Metro and mobility hub"},
    {
        "id": "thrippunithura",
        "name": "Thrippunithura",
        "character": "Royal Kochi and temple heritage",
    },
    {"id": "kakkanad", "name": "Kakkanad", "character": "Eastern city and green escapes"},
    {"id": "kalamassery", "name": "Kalamassery", "character": "Museums and university district"},
    {"id": "willingdon", "name": "Willingdon Island", "character": "Harbour views"},
]

_SOURCE_AREA_ALIASES = {
    "Ernakulam": "ernakulam",
    "Marine Drive": "ernakulam",
    "Fort Kochi": "fort-kochi",
    "Mattancherry": "mattancherry",
    "Willingdon Island": "willingdon",
}


def _area_id(area):
    return _SOURCE_AREA_ALIASES.get(area) or re.sub(r"[^a-z0-9]+", "-", area.lower()).strip("-")


_SOURCE_PLACES_PATH = Path(__file__).with_name("data") / "kochi_places.json"
with _SOURCE_PLACES_PATH.open(encoding="utf-8") as source_file:
    _SOURCE_PLACES = json.load(source_file)

for source_place in _SOURCE_PLACES:
    if not isinstance(source_place, dict) or not source_place.get("id"):
        raise ValueError("Every imported Kochi place must be an object with an id")
    area = source_place.get("area")
    if not isinstance(area, str) or not area.strip():
        raise ValueError(f"Imported Kochi place {source_place['id']} has no area")
    area_id = _area_id(area)
    if area_id not in {region["id"] for region in REGIONS}:
        REGIONS.append(
            {"id": area_id, "name": area, "character": "Imported illustrative demo location"}
        )
REGION_IDS = {region["id"] for region in REGIONS}
REGION_NAMES = {region["id"]: region["name"] for region in REGIONS}

_AREA_BY_ID = {
    "nets": "fort-kochi",
    "church": "fort-kochi",
    "kashi": "fort-kochi",
    "beach": "fort-kochi",
    "gallery": "fort-kochi",
    "basilica": "fort-kochi",
    "theatre": "fort-kochi",
    "princess": "fort-kochi",
    "ferry": "fort-kochi",
    "palace": "mattancherry",
    "jewtown": "mattancherry",
    "synagogue": "mattancherry",
    "cafe": "mattancherry",
    "market": "mattancherry",
    "sadya": "mattancherry",
    "promenade": "ernakulam",
    "park": "ernakulam",
    "island": "willingdon",
}


def place(id, name, category, lat, lng, cost, duration, hours, tip, scores, area=None, count=24):
    area = area or _AREA_BY_ID.get(id)
    if area not in REGION_IDS:
        raise ValueError(f"Unknown Kochi area for {id}: {area}")
    return dict(
        id=id,
        name=name,
        category=category,
        area=area,
        area_name=REGION_NAMES[area],
        lat=lat,
        lng=lng,
        cost=cost,
        price_tier="premium" if cost >= 2500 else "standard",
        duration=duration,
        opens=hours[0],
        closes=hours[1],
        tip=tip,
        slh=dict(
            safety=scores[0],
            legitimacy=scores[1],
            hygiene=scores[2],
            reviews=count,
            reviewed_at="2026-09-01",
            source="Illustrative seed data",
        ),
        demo=True,
    )


_SOURCE_CATEGORY_MAP = {
    "restaurants": "Food",
    "local food": "Food",
    "street food": "Food",
    "cafes": "Food",
    "art": "Art",
    "shopping": "Shopping",
    "markets": "Shopping",
    "heritage": "Culture",
    "religious": "Culture",
    "culture": "Culture",
    "museums": "Culture",
    "nature": "Nature",
    "beaches": "Nature",
    "parks": "Nature",
    "waterfront": "Nature",
}


def _source_hours(best_time):
    periods = set(best_time)
    if periods == {"morning"}:
        return 8, 14
    if periods == {"afternoon"}:
        return 11, 18
    if periods == {"evening"}:
        return 16, 22
    if periods == {"night"}:
        return 18, 22
    return 8, 22


def _import_source_place(source_place):
    area_id = _area_id(source_place["area"])
    opens, closes = _source_hours(source_place["best_time"])
    category = _SOURCE_CATEGORY_MAP.get(source_place["category"], "Hidden gems")
    imported = dict(source_place)
    imported.update(
        area=area_id,
        area_name=REGION_NAMES[area_id],
        lat=source_place["location"]["latitude"],
        lng=source_place["location"]["longitude"],
        category=category,
        source_category=source_place["category"],
        cost=source_place["estimated_cost_per_person"],
        price_tier=("premium" if source_place["estimated_cost_per_person"] >= 2500 else "standard"),
        duration=source_place["average_visit_minutes"],
        opens=opens,
        closes=closes,
        tip=source_place["local_tip"],
        slh=dict(
            safety=None,
            legitimacy=None,
            hygiene=None,
            reviews=0,
            reviewed_at=None,
            source="No SLH dimensions supplied in source data",
        ),
        demo=True,
    )
    return imported


PLACES = [
    place(
        "nets",
        "Chinese Fishing Nets",
        "Nature",
        9.9677,
        76.2425,
        0,
        60,
        (8, 18),
        "Go early for softer light. Ask before photographing working fishers.",
        (4.5, 4.8, 4.2),
    ),
    place(
        "church",
        "St. Francis Church",
        "Culture",
        9.9657,
        76.241,
        0,
        45,
        (9, 17),
        "Dress respectfully and keep your voice low inside.",
        (4.7, 4.9, 4.5),
    ),
    place(
        "kashi",
        "Kashi Art Café",
        "Food",
        9.9656,
        76.2428,
        350,
        60,
        (9, 18),
        "Leave time to enjoy the art alongside your coffee.",
        (4.6, 4.7, 4.6),
    ),
    place(
        "beach",
        "Fort Kochi Beach",
        "Nature",
        9.9638,
        76.2387,
        0,
        75,
        (8, 18),
        "Enjoy the shoreline walk; this plan does not recommend swimming.",
        (4.2, 4.8, 3.8),
    ),
    place(
        "palace",
        "Mattancherry Palace",
        "Culture",
        9.9579,
        76.2595,
        100,
        75,
        (10, 17),
        "Confirm the opening day before visiting; the murals deserve a slow look.",
        (4.6, 4.9, 4.5),
    ),
    place(
        "jewtown",
        "Jew Town",
        "Culture",
        9.9572,
        76.2591,
        0,
        60,
        (9, 18),
        "Browse the small shops and ask before taking photos inside.",
        (4.4, 4.6, 4.2),
    ),
    place(
        "synagogue",
        "Paradesi Synagogue",
        "Culture",
        9.9578,
        76.2593,
        50,
        45,
        (10, 16),
        "Religious holidays can change access. Check locally before setting out.",
        (4.6, 4.9, 4.6),
    ),
    place(
        "cafe",
        "Mattancherry Tea Stop",
        "Food",
        9.9583,
        76.2598,
        150,
        45,
        (10, 18),
        "Illustrative food stop: choose a clearly priced, well-maintained local café.",
        (4.3, 4.3, 4.5),
    ),
    place(
        "market",
        "Spice Market Walk",
        "Food",
        9.9555,
        76.2601,
        100,
        60,
        (9, 17),
        "Compare prices and buy spices in clearly labeled, sealed packs.",
        (4.3, 4.4, 4.2),
    ),
    place(
        "sadya",
        "Kerala Sadya Lunch",
        "Food",
        9.9587,
        76.2585,
        350,
        75,
        (12, 15),
        "Illustrative lunch stop. Ask about ingredients and allergens before ordering.",
        (4.5, 4.5, 4.6),
    ),
    place(
        "promenade",
        "Marine Drive Promenade",
        "Nature",
        9.9814,
        76.2753,
        0,
        60,
        (8, 18),
        "Use the public waterfront paths and carry drinking water.",
        (4.3, 4.7, 4.0),
    ),
    place(
        "park",
        "Subhash Bose Park",
        "Nature",
        9.9695,
        76.2771,
        0,
        60,
        (10, 18),
        "Take a quiet break and use the marked waste bins.",
        (4.5, 4.8, 4.4),
    ),
    place(
        "island",
        "Willingdon Island Viewpoint",
        "Nature",
        9.9496,
        76.2756,
        100,
        75,
        (9, 17),
        "Stay in public areas; some island facilities have restricted access.",
        (4.2, 4.5, 4.1),
    ),
    place(
        "gallery",
        "David Hall Gallery",
        "Art",
        9.9638,
        76.2405,
        100,
        60,
        (10, 17),
        "Check which exhibition is on before your visit.",
        (4.6, 4.8, 4.6),
    ),
    place(
        "basilica",
        "Santa Cruz Basilica",
        "Culture",
        9.9632,
        76.2431,
        0,
        45,
        (9, 17),
        "Plan around services and respect photography restrictions.",
        (4.7, 4.9, 4.6),
    ),
    place(
        "theatre",
        "Kerala Kathakali Centre",
        "Art",
        9.9631,
        76.2433,
        500,
        90,
        (15, 19),
        "Confirm performance times and tickets with the venue.",
        (4.6, 4.8, 4.4),
    ),
    place(
        "princess",
        "Princess Street",
        "Hidden gems",
        9.9661,
        76.2421,
        0,
        45,
        (9, 18),
        "Look up at the old façades and stop into independent shops.",
        (4.4, 4.6, 4.3),
    ),
    place(
        "ferry",
        "Fort Kochi Ferry Waterfront",
        "Hidden gems",
        9.9673,
        76.2448,
        50,
        45,
        (8, 18),
        "Watch the ferries from public areas. Boat tickets are not included.",
        (4.2, 4.7, 4.0),
    ),
    place(
        "broadway",
        "Broadway Market",
        "Hidden gems",
        9.9817,
        76.2810,
        100,
        75,
        (9, 18),
        "Go in daylight, keep valuables close, and compare clearly marked prices.",
        (4.2, 4.6, 4.0),
        "ernakulam",
    ),
    place(
        "shiva-temple",
        "Ernakulam Shiva Temple",
        "Culture",
        9.9703,
        76.2797,
        0,
        45,
        (5, 20),
        "Dress respectfully and check current worship-time visitor access.",
        (4.6, 4.9, 4.5),
        "ernakulam",
    ),
    place(
        "panampilly-park",
        "Panampilly Nagar Central Park",
        "Nature",
        9.9593,
        76.2940,
        0,
        60,
        (6, 20),
        "Visit in the cooler morning or evening and use the public paths.",
        (4.5, 4.6, 4.3),
        "panampilly",
    ),
    place(
        "panampilly-walk",
        "Panampilly Nagar Café Walk",
        "Food",
        9.9612,
        76.2928,
        450,
        90,
        (10, 21),
        "A sample neighbourhood walk: choose busy venues with displayed prices.",
        (4.5, 4.4, 4.5),
        "panampilly",
    ),
    place(
        "kadavanthra-market",
        "Kadavanthra Market Walk",
        "Hidden gems",
        9.9670,
        76.2992,
        100,
        60,
        (8, 18),
        "A sample local-market stop; visit by day and ask before photographing vendors.",
        (4.2, 4.4, 4.1),
        "kadavanthra",
    ),
    place(
        "lulu",
        "Lulu Mall Kochi",
        "Shopping",
        10.0266,
        76.3085,
        500,
        120,
        (10, 22),
        "Use the metro at Edappally when practical and check venue hours directly.",
        (4.7, 4.8, 4.7),
        "edappally",
    ),
    place(
        "edappally-church",
        "St. George Forane Church",
        "Culture",
        10.0277,
        76.3071,
        0,
        45,
        (6, 20),
        "Plan around services, dress respectfully, and keep photography discreet.",
        (4.7, 4.9, 4.6),
        "edappally",
    ),
    place(
        "changampuzha",
        "Changampuzha Park",
        "Nature",
        10.0183,
        76.3008,
        0,
        60,
        (6, 20),
        "Check the day's cultural programme and stay on the public park paths.",
        (4.5, 4.6, 4.4),
        "edappally",
    ),
    place(
        "stadium",
        "Jawaharlal Nehru Stadium Precinct",
        "Hidden gems",
        10.0048,
        76.3007,
        0,
        45,
        (6, 20),
        "Use the public exterior spaces; match days can change traffic and access.",
        (4.3, 4.5, 4.2),
        "palarivattom",
    ),
    place(
        "palarivattom-food",
        "Palarivattom Food Walk",
        "Food",
        10.0027,
        76.3062,
        400,
        90,
        (11, 21),
        "A sample food trail: favour busy kitchens and ask about allergens.",
        (4.3, 4.3, 4.4),
        "palarivattom",
    ),
    place(
        "vyttila-water-metro",
        "Vyttila Water Metro Terminal",
        "Hidden gems",
        9.9665,
        76.3214,
        50,
        45,
        (7, 19),
        "Treat this as a transport experience and confirm the live sailing schedule.",
        (4.5, 4.8, 4.4),
        "vyttila",
    ),
    place(
        "hill-palace",
        "Hill Palace Museum",
        "Culture",
        9.9527,
        76.3639,
        100,
        120,
        (9, 17),
        "Allow time for the grounds and verify the weekly closure before travelling.",
        (4.6, 4.9, 4.5),
        "thrippunithura",
    ),
    place(
        "poornathrayeesa",
        "Sree Poornathrayeesa Temple",
        "Culture",
        9.9497,
        76.3438,
        0,
        60,
        (5, 20),
        "Check visitor access and dress rules; festival days can be especially busy.",
        (4.6, 4.9, 4.5),
        "thrippunithura",
    ),
    place(
        "kadambrayar",
        "Kadambrayar Riverside",
        "Nature",
        10.0046,
        76.3734,
        100,
        90,
        (7, 18),
        "Visit in daylight, check weather, and use established public activity areas.",
        (4.2, 4.4, 4.1),
        "kakkanad",
    ),
    place(
        "kerala-museum",
        "Museum of Kerala History",
        "Art",
        10.0459,
        76.3171,
        200,
        90,
        (10, 17),
        "Confirm current opening days and exhibition access before taking the metro.",
        (4.6, 4.8, 4.5),
        "kalamassery",
    ),
    place(
        "private-heritage-guide",
        "Private Heritage Guide",
        "Culture",
        9.9657,
        76.2420,
        3500,
        150,
        (9, 17),
        "Illustrative premium experience: agree on a licensed guide, written inclusions, and the full price before paying.",
        (4.6, 4.7, 4.5),
        "fort-kochi",
    ),
    place(
        "private-harbour-cruise",
        "Private Kochi Harbour Cruise",
        "Nature",
        9.9814,
        76.2753,
        5500,
        150,
        (9, 18),
        "Illustrative premium experience: verify the operator, vessel, safety equipment, route, cancellation terms, and total price.",
        (4.4, 4.6, 4.3),
        "ernakulam",
    ),
    place(
        "kochi-kitchen",
        "Kochi Kitchen at Kochi Marriott",
        "Food",
        10.0273,
        76.3088,
        3200,
        90,
        (12, 22),
        "Illustrative per-person dining estimate. Confirm the current buffet or à-la-carte price and inclusions directly.",
        (4.7, 4.8, 4.7),
        "edappally",
    ),
    place(
        "all-spice",
        "All Spice at Courtyard Kochi Infopark",
        "Food",
        10.0130,
        76.3623,
        2800,
        90,
        (19, 23),
        "Illustrative fine-dining estimate. Confirm current opening hours, menu prices, taxes, and reservation terms.",
        (4.6, 4.8, 4.6),
        "kakkanad",
    ),
    place(
        "skygrill",
        "SkyGrill at Crowne Plaza Kochi",
        "Food",
        9.9339,
        76.3186,
        3500,
        90,
        (18, 23),
        "Illustrative rooftop-dinner estimate. Confirm the current menu, taxes, dress expectations, and reservation.",
        (4.6, 4.8, 4.6),
        "vyttila",
    ),
    place(
        "premium-wellness",
        "Premium Ayurvedic Wellness Session",
        "Hidden gems",
        9.9612,
        76.2928,
        4500,
        120,
        (10, 20),
        "Illustrative premium experience: choose a reputable provider and confirm practitioner credentials, treatment, and total price.",
        (4.5, 4.6, 4.7),
        "panampilly",
    ),
]

_catalog_ids = {catalog_place["id"] for catalog_place in PLACES}
_imported_places = [_import_source_place(source_place) for source_place in _SOURCE_PLACES]
if _catalog_ids & {source_place["id"] for source_place in _imported_places}:
    raise ValueError("Imported Kochi place IDs must not collide with the curated catalog")
PLACES.extend(_imported_places)

BY_ID = {p["id"]: p for p in PLACES}
TEMPLATE_STOPS = {
    "slow-kochi": [
        "nets",
        "church",
        "kashi",
        "beach",
        "palace",
        "jewtown",
        "cafe",
        "promenade",
    ],
    "heritage-trail": ["palace", "jewtown", "synagogue", "cafe"],
    "taste-kochi": ["kashi", "market", "sadya", "cafe"],
    "coastal-reset": [
        "nets",
        "beach",
        "promenade",
        "park",
        "island",
        "kashi",
        "cafe",
        "market",
        "sadya",
    ],
    "royal-kochi": ["hill-palace", "poornathrayeesa", "panampilly-park"],
    "city-and-style": [
        "broadway",
        "promenade",
        "shiva-temple",
        "panampilly-walk",
        "panampilly-park",
    ],
    "north-kochi": ["kerala-museum", "changampuzha", "edappally-church", "lulu"],
    "water-and-green": ["vyttila-water-metro", "kadambrayar", "panampilly-park"],
}


def slh_score(slh):
    values = [slh.get(k) for k in ("safety", "legitimacy", "hygiene")]
    if any(
        not isinstance(v, (float, int)) or isinstance(v, bool) or not 1 <= v <= 5 for v in values
    ):
        return None
    return round(sum(values) / 15 * 100)
