export const photos = {
  coast: '/images/kochi.jpg',
  heritage: '/images/heritage.jpg',
  food: '/images/food.jpg',
  sunset: '/images/fort-kochi-sunset.jpg',
  palace: '/images/hill-palace.jpg',
  city: '/images/marine-drive.jpg',
  metro: '/images/edappally-metro.jpg',
  waterMetro: '/images/vyttila-water-metro.jpg',
};
export const templates = [
  {
    id: 'slow-kochi',
    title: 'The slow side of Kochi',
    subtitle: 'Sea breezes, old streets & a really good cup of coffee.',
    days: 2,
    cost: 1800,
    category: 'Hidden gems',
    image: photos.sunset,
    imageAlt: 'Fort Kochi Beach at sunset',
    creator: 'Ananya M.',
    initials: 'AM',
    role: 'Kochi local',
    color: '#e9d6b5',
    tags: ['Culture', 'Food', 'Nature'],
    travelTypes: ['solo', 'group', 'family'],
    areas: ['Fort Kochi', 'Mattancherry', 'Ernakulam & Marine Drive'],
    stops: ['nets', 'church', 'kashi', 'beach', 'palace', 'jewtown', 'cafe', 'promenade'],
    featured: true,
  },
  {
    id: 'heritage-trail',
    title: 'Stories in every street',
    subtitle: 'A walk through the many worlds of Mattancherry.',
    days: 1,
    cost: 850,
    category: 'Culture & heritage',
    image: photos.heritage,
    imageAlt: 'Interior of Mattancherry Palace',
    creator: 'Arjun R.',
    initials: 'AR',
    role: 'History enthusiast',
    color: '#d5dfec',
    tags: ['Culture', 'Art'],
    travelTypes: ['solo', 'group'],
    areas: ['Mattancherry'],
    stops: ['palace', 'jewtown', 'synagogue', 'cafe'],
  },
  {
    id: 'taste-kochi',
    title: 'A taste of the real Kochi',
    subtitle: 'Banana-leaf lunches, little cafés & big flavours.',
    days: 1,
    cost: 1100,
    category: 'Food trail',
    image: photos.food,
    imageAlt: 'Kerala sadya served on a banana leaf',
    creator: 'Meera K.',
    initials: 'MK',
    role: 'Food explorer',
    color: '#e7d5de',
    tags: ['Food', 'Culture'],
    travelTypes: ['solo', 'group', 'family'],
    areas: ['Fort Kochi', 'Mattancherry'],
    stops: ['kashi', 'market', 'sadya', 'cafe'],
  },
  {
    id: 'coastal-reset',
    title: 'Salt air & slower mornings',
    subtitle: 'A little less rushing. A lot more waterfront.',
    days: 3,
    cost: 2600,
    category: 'Outdoors',
    image: photos.coast,
    imageAlt: 'Chinese fishing nets on the Kochi waterfront',
    creator: 'Dev P.',
    initials: 'DP',
    role: 'Weekend wanderer',
    color: '#d9e5c8',
    tags: ['Nature', 'Food'],
    travelTypes: ['solo', 'group', 'family'],
    areas: ['Fort Kochi', 'Mattancherry', 'Ernakulam & Marine Drive', 'Willingdon Island'],
    stops: ['nets', 'beach', 'promenade', 'park', 'island', 'kashi', 'cafe', 'market', 'sadya'],
  },
  {
    id: 'city-and-style',
    title: 'Downtown to Panampilly',
    subtitle: 'Markets, waterfront light & the city’s café side.',
    days: 2,
    cost: 1700,
    category: 'City life',
    image: photos.city,
    imageAlt: 'Marine Drive in Kochi',
    creator: 'Riya J.',
    initials: 'RJ',
    role: 'Ernakulam local',
    color: '#d5dfec',
    tags: ['Food', 'Culture', 'Hidden gems'],
    travelTypes: ['solo', 'group'],
    areas: ['Ernakulam & Marine Drive', 'Panampilly Nagar'],
    stops: ['broadway', 'promenade', 'shiva-temple', 'panampilly-walk', 'panampilly-park'],
  },
  {
    id: 'north-kochi',
    title: 'Edappally, made local',
    subtitle: 'A neighbourhood park, church heritage & modern Edappally.',
    days: 1,
    cost: 1250,
    category: 'Culture & shopping',
    image: photos.metro,
    imageAlt: 'Kochi Metro at Edappally station',
    creator: 'Fahad K.',
    initials: 'FK',
    role: 'Edappally local',
    color: '#d9e5c8',
    tags: ['Culture', 'Art', 'Shopping'],
    travelTypes: ['solo', 'group', 'family'],
    areas: ['Edappally'],
    stops: ['changampuzha', 'edappally-church', 'lulu'],
  },
  {
    id: 'water-and-green',
    title: 'Water Metro to the green heart',
    subtitle: 'A transit-led day connecting Vyttila and Panampilly Nagar.',
    days: 1,
    cost: 850,
    category: 'Outdoors',
    image: photos.waterMetro,
    imageAlt: 'Vyttila Water Metro station',
    creator: 'Akhil V.',
    initials: 'AV',
    role: 'Kochi explorer',
    color: '#cfe3df',
    tags: ['Nature', 'Hidden gems'],
    travelTypes: ['solo', 'group', 'family'],
    areas: ['Vyttila', 'Panampilly Nagar'],
    stops: ['vyttila-water-metro', 'panampilly-park'],
  },
];
export const interests = [
  'All experiences',
  'Food',
  'Culture',
  'Nature',
  'Art',
  'Hidden gems',
  'Shopping',
];
export const money = (value) =>
  new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(value);
export function slhScore(slh) {
  if (
    !slh ||
    ['safety', 'legitimacy', 'hygiene'].some(
      (key) => !Number.isFinite(slh[key]) || slh[key] < 1 || slh[key] > 5,
    )
  )
    return null;
  return Math.round(((slh.safety + slh.legitimacy + slh.hygiene) / 15) * 100);
}
export function templateSLH(template, places) {
  const stops = template.stops.map((id) => places.find((p) => p.id === id));
  if (stops.some((p) => !p || slhScore(p.slh) === null)) return null;
  return Object.fromEntries([
    ...['safety', 'legitimacy', 'hygiene'].map((key) => [
      key,
      stops.reduce((sum, p) => sum + p.slh[key], 0) / stops.length,
    ]),
    ['reviews', stops.reduce((sum, p) => sum + p.slh.reviews, 0)],
    ['reviewed_at', '2026-09-01'],
  ]);
}
