export const photos = {
  coast: '/images/kochi.jpg',
  heritage: '/images/heritage.jpg',
  food: '/images/food.jpg',
};
export const templates = [
  {
    id: 'slow-kochi',
    title: 'The slow side of Kochi',
    subtitle: 'Sea breezes, old streets & a really good cup of coffee.',
    days: 2,
    cost: 1800,
    category: 'Hidden gems',
    image: photos.coast,
    creator: 'Ananya M.',
    initials: 'AM',
    role: 'Kochi local',
    color: '#e9d6b5',
    tags: ['Culture', 'Food', 'Nature'],
    areas: ['Fort Kochi', 'Mattancherry', 'Ernakulam & Marine Drive'],
    stops: ['nets', 'church', 'kashi', 'beach', 'palace', 'jewtown', 'cafe', 'promenade'],
    featured: true,
  },
  {
    id: 'heritage-trail',
    title: 'Stories in every street',
    subtitle: 'A walk through the many worlds of Mattancherry.',
    days: 1,
    cost: 850,
    category: 'Culture & heritage',
    image: photos.heritage,
    creator: 'Arjun R.',
    initials: 'AR',
    role: 'History enthusiast',
    color: '#d5dfec',
    tags: ['Culture', 'Art'],
    areas: ['Mattancherry'],
    stops: ['palace', 'jewtown', 'synagogue', 'cafe'],
  },
  {
    id: 'taste-kochi',
    title: 'A taste of the real Kochi',
    subtitle: 'Banana-leaf lunches, little cafés & big flavours.',
    days: 1,
    cost: 1100,
    category: 'Food trail',
    image: photos.food,
    creator: 'Meera K.',
    initials: 'MK',
    role: 'Food explorer',
    color: '#e7d5de',
    tags: ['Food', 'Culture'],
    areas: ['Fort Kochi', 'Mattancherry'],
    stops: ['kashi', 'market', 'sadya', 'cafe'],
  },
  {
    id: 'coastal-reset',
    title: 'Salt air & slower mornings',
    subtitle: 'A little less rushing. A lot more waterfront.',
    days: 3,
    cost: 2600,
    category: 'Outdoors',
    image: photos.coast,
    creator: 'Dev P.',
    initials: 'DP',
    role: 'Weekend wanderer',
    color: '#d9e5c8',
    tags: ['Nature', 'Food'],
    areas: ['Fort Kochi', 'Mattancherry', 'Ernakulam & Marine Drive', 'Willingdon Island'],
    stops: ['nets', 'beach', 'promenade', 'park', 'island', 'kashi', 'cafe', 'market', 'sadya'],
  },
  {
    id: 'royal-kochi',
    title: 'Royal Kochi, beyond the coast',
    subtitle: 'Palace grounds, temple heritage & a green city pause.',
    days: 1,
    cost: 900,
    category: 'Culture & heritage',
    image: photos.heritage,
    creator: 'Nila S.',
    initials: 'NS',
    role: 'Thrippunithura local',
    color: '#ead9c5',
    tags: ['Culture', 'Nature'],
    areas: ['Thrippunithura', 'Panampilly Nagar'],
    stops: ['hill-palace', 'poornathrayeesa', 'panampilly-park'],
  },
  {
    id: 'city-and-style',
    title: 'Downtown to Panampilly',
    subtitle: 'Markets, waterfront light & the city’s café side.',
    days: 2,
    cost: 1700,
    category: 'City life',
    image: photos.food,
    creator: 'Riya J.',
    initials: 'RJ',
    role: 'Ernakulam local',
    color: '#d5dfec',
    tags: ['Food', 'Culture', 'Hidden gems'],
    areas: ['Ernakulam & Marine Drive', 'Panampilly Nagar'],
    stops: ['broadway', 'promenade', 'shiva-temple', 'panampilly-walk', 'panampilly-park'],
  },
  {
    id: 'north-kochi',
    title: 'Metro north, made local',
    subtitle: 'Museum stories, a neighbourhood park & modern Edappally.',
    days: 1,
    cost: 1250,
    category: 'Culture & shopping',
    image: photos.heritage,
    creator: 'Fahad K.',
    initials: 'FK',
    role: 'Kalamassery local',
    color: '#d9e5c8',
    tags: ['Culture', 'Art', 'Shopping'],
    areas: ['Kalamassery', 'Edappally'],
    stops: ['kerala-museum', 'changampuzha', 'edappally-church', 'lulu'],
  },
  {
    id: 'water-and-green',
    title: 'Water Metro to the green edge',
    subtitle: 'A transit-led day from Vyttila to Kakkanad’s riverside.',
    days: 1,
    cost: 850,
    category: 'Outdoors',
    image: photos.coast,
    creator: 'Akhil V.',
    initials: 'AV',
    role: 'Kakkanad explorer',
    color: '#cfe3df',
    tags: ['Nature', 'Hidden gems'],
    areas: ['Vyttila', 'Kakkanad', 'Panampilly Nagar'],
    stops: ['vyttila-water-metro', 'kadambrayar', 'panampilly-park'],
  },
];
export const interests = [
  'All experiences',
  'Food',
  'Culture',
  'Nature',
  'Art',
  'Hidden gems',
  'Shopping',
];
export const money = (value) =>
  new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(value);
export function slhScore(slh) {
  if (
    !slh ||
    ['safety', 'legitimacy', 'hygiene'].some(
      (key) => !Number.isFinite(slh[key]) || slh[key] < 1 || slh[key] > 5,
    )
  )
    return null;
  return Math.round(((slh.safety + slh.legitimacy + slh.hygiene) / 15) * 100);
}
export function templateSLH(template, places) {
  const stops = template.stops.map((id) => places.find((p) => p.id === id));
  if (stops.some((p) => !p || slhScore(p.slh) === null)) return null;
  return Object.fromEntries([
    ...['safety', 'legitimacy', 'hygiene'].map((key) => [
      key,
      stops.reduce((sum, p) => sum + p.slh[key], 0) / stops.length,
    ]),
    ['reviews', stops.reduce((sum, p) => sum + p.slh.reviews, 0)],
    ['reviewed_at', '2026-09-01'],
  ]);
}
